name: Build rbxlx-to-rojo
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: rbxlx-to-rojo
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install Rust
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Install GTK
        if: runner.os == 'Linux'
        run: |
          sudo apt install libgtk-3-dev -y
      - name: Build (All Features)
        run: cargo build --locked --release --all-features