name: Build rbxlx-to-rojo
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: rbxlx-to-rojo
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: rbxlx-to-rojo-linux
            path: rbxlx-to-rojo
          - os: maxos-latest
            name: rbxlx-to-rojo-macos
            path: rbxlx-to-rojo
          - os: windows-latest
            name: rbxlx-to-rojo-
            path: rbxlx-to-rojo.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install Rust
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Install GTK
        if: runner.os == 'Linux'
        run: |
          sudo apt install libgtk-3-dev -y
      - name: Build (All Features)
        run: cargo build --locked --release --all-features
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{matrix.name}}
          path: ./target/release/${{matrix.path}}
