name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: rbxlx-to-rojo-linux
            path: rbxlx-to-rojo
          - os: macos-latest
            name: rbxlx-to-rojo-macos
            path: rbxlx-to-rojo
          - os: windows-latest
            name: rbxlx-to-rojo-windows
            path: rbxlx-to-rojo.exe
    name: Release ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install Rust
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Install GTK
        if: runner.os == 'Linux'
        run: |
          sudo apt install libgtk-3-dev zip -y
      - name: Build (All Features)
        run: cargo build --locked --release --all-features
      - name: Zip File Linux / macOS
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          mv ./target/release/${{matrix.path}} ./${{matrix.path}}
          zip ./${{matrix.name}}.zip ./${{matrix.path}}
      - name: Rename File Windows
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path ./target/release/${{matrix.path}} -DestinationPath ${{matrix.name}}.zip
      - name: Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: ${{matrix.name}}.zip